### ISSUE TITLE
Provide a UI to Fetch API via OpenAPI

### ISSUE THREAD

**Issue by infojunkie** [meedan/check#10]
**Tell us about your request**
Use the latest version of OpenAPI (3.x) to provide a UI for the Fetch API. Evaluate [OpenAPI Generator](https://openapi-generator.tech/) as possible technology.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Testing and debugging an API during development is much easier when a UI exists to make API calls.

**Are you currently working around the issue?**
Using `curl` to craft API calls, or using throwaway ruby scripts for specific functions.

**Comment by RanadeepPolavarapu** [comment]
I can grab this if that's okay.

**Comment by danielafeitosa** [comment]
It's okay @RanadeepPolavarapu. If you want to work on this, you can check this good example of what is needed here: meedan/pender#233
