### ISSUE TITLE
Restore screenshot archiver to Pender

### ISSUE THREAD

**Issue by infojunkie** [meedan/check#13]
**Tell us about your request**
Pender 's [screenshotting function was removed](https://github.com/meedan/pender/commit/3f7116970f38bf0b08e5e1263af25a52f218ef04) because it was a resource drain that endangered the deployment. Since then, we have introduced [Narcissus](https://github.com/meedan/narcissus) as a flexible and efficient screenshotting service, that Pender can now call for its own needs. This request is about restoring the Pender `screenshot` archiver - using Narcissus as the screenshot provider. 

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Taking a screenshot of a media being used in a fact-check or investigation is important, because the media could be subsequently modified or taken down. 

**Are you currently working around the issue?**
Manually taking a screenshot and attaching it to a Check item as an image comment.

**Implementation hints**
- Emulate the removed [`MediaScreenshotArchiver`](https://github.com/meedan/pender/blob/3f7116970f38bf0b08e5e1263af25a52f218ef04/app/models/concerns/media_screenshot_archiver.rb) - by calling Narcissus instead of the obsolete and inefficient implementation.
- Restore tests

**Comment by avats-dev** [comment]
@infojunkie I want to contribute. Can you guide me a bit how to implement this, as I'm new to this codebase? Thanks.

**Comment by danielafeitosa** [comment]
@avats-dev thank you for your interest! 

First you need to [add a new archiver to Pender](https://github.com/meedan/pender#how-to-add-a-new-archiver).
The method `archive_to_screenshot`  you'll create should call [Narcissus](https://github.com/meedan/narcissus/) to take a screenshot of the URL in background and add it to a `screenshot` key on media data.

You can check how Narcissus is called on CheckAPI: https://github.com/meedan/check-api/blob/develop/config/initializers/report_designer.rb#L92-L97

To run locally you need to clone [Pender repository](https://github.com/meedan/pender) and start it with `docker-compose up`. Let us know if you have any difficulty.

**Comment by avats-dev** [comment]
Thanks @danielafeitosa , I will get started on this and let you know if I'm stuck.
