### ISSUE TITLE
Fetch query Web interface

### ISSUE THREAD

**Issue by infojunkie** [meedan/check#16]
**Tell us about your request**
Create a Web interface to [Fetch's query API](https://github.com/meedan/check/issues/15), modeled after [Google's Fact Check Explorer](https://toolbox.google.com/factcheck/explorer).

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
A search Web UI is a great demo of the capabilities of Fetch, decoupled from Check. 

**Implementation hints**
- Implement the UI using React.
- Organize the code in a subfolder `fetch/web`.

**Comment by gabrielrab** [comment]
@infojunkie I would like to work on this issue! Please assign this to me!

**Comment by infojunkie** [comment]
@gabrielrab thanks! You can start working on your own forkof [Fetch](https://github.com/meedan/fetch) and submit a PR when ready :pray:

**Comment by imabp** [comment]
Are you working on it @gabrielrab

**Comment by danielafeitosa** [comment]
@imabp there wasn't a PR for this yet.. You can work on it if you want :smile:
