### ISSUE TITLE
Remove inline styling in favor of material-ui makeStyles

### ISSUE THREAD

**Issue by amoedoamorim** [meedan/check#17]
**Tell us about your request**
Remove inline styling in favor of material-ui makeStyles

**Which service(s) is this request for?**
- Check Web
- Check Mark

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
In order to achieve a better code organization, we're shifting away from inline styling.
Also, by using material-ui's css-in-js solution we benefit from the rtl layout handling.
When we need to apply custom styles to material-ui components it makes sense to use makeStyles to do so.

**Sample code locations (not limited to):**

https://github.com/meedan/check-web/blob/develop/src/app/components/FlashMessage.js#L65
https://github.com/meedan/check-web/blob/develop/src/app/components/layout/ColorPicker.js#L28
https://github.com/meedan/check-web/blob/develop/src/app/components/source/UserPrivacy.js

**Comment by deepakchethan** [comment]
Hello @amoedoamorim, I can take this up if it's up for grabs

**Comment by KarenEfereyan** [comment]
M here also

**Comment by amoedoamorim** [comment]
@deepakchethan I have assigned it to you! Thanks for your interest. Please go ahead and let us know if you have any trouble.

**Comment by abhisheknaiidu** [comment]
@amoedoamorim If it's not being worked on, I want to work on this. Thanks

**Comment by aryangulati** [comment]
Yeah me too if it not resolved yet
