### ISSUE TITLE
Replace `prop.intl.formatMessage` with `<FormattedMessage />`

### ISSUE THREAD

**Issue by amoedoamorim** [meedan/check#20]
**Tell us about your request**
Replace `prop.intl.formatMessage` with `<FormattedMessage />`

**Which service(s) is this request for?**
Let us know which services(s) you want this for?
- Check Web

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
As per our recent coding practices we are now favoring the <FormattedMessage /> usage of react-intl instead of 
`prop.intl.formatMessage`. `<FormattedMessage />` can receive a function as a child to which will be passed the translated string.
It is useful when it's required to pass a string rather than a <span> element.

**Sample code locations (not limited to):**
https://github.com/meedan/check-web/blob/develop/src/app/components/media/CreateRelatedMediaDialog.js#L100
https://github.com/meedan/check-web/blob/develop/src/app/components/task/EditTaskDialog.js#L241
https://github.com/meedan/check-web/blob/develop/src/app/components/task/EditTaskDialog.js#L247

**Comment by sparkingdark** [comment]
Assign it to me i want to work @amoedoamorim .

**Comment by amoedoamorim** [comment]
Awesome @sparkingdark ! Thank you for your interest! I have assigned the issue to you, please go ahead!

**Comment by sparkingdark** [comment]
Thanks Am i need to recode it to the given instruction?

**Comment by sparkingdark** [comment]
Hey @amoedoamorim can you tell me how to build it and run in my local computer I got error while i run 

```
docker-compose exec web npm run test:unit
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

```

Am i need to create a file or need to clone all the repo recursively?

**Comment by sparkingdark** [comment]
@amoedoamorim  can you check my pull request in check-web ?

**Comment by ShyamPraveenSingh** [comment]
Hi, I would like to work on this issue.
Can you please explain it to me about the issue.

**Comment by ShyamPraveenSingh** [comment]
Hi @amoedoamorim I would like to work on it. Please assign it to me.

**Comment by amoedoamorim** [comment]
> Am i need to create a file or need to clone all the repo recursively?

Yes, to run Check locally you need to clone the whole check repo recursively. Please follow the steps at https://github.com/meedan/check#quick-start and let us know if you have any difficulty.

**Comment by sparkingdark** [comment]
Okay

**Comment by gabrielrab** [comment]
Hi!
Could you assign me this problem, I sent [my PR](https://github.com/meedan/check-web/pull/719) with resolution of that issue.

**Comment by swapniljha001** [comment]
Is this issue still open?

**Comment by sneha-mehta** [comment]
Is it still open?? Can I make a contribution too?

**Comment by NilmaPeiris** [comment]
hey  I sent my PR with resolution of that issue.

**Comment by ShubhamPatel33** [comment]
hi @sparkingdark ,i want  to work on it can you just give me a brief and in which document i have to do the replace work ?
Regards,
Shubham patel
