### ISSUE TITLE
Add a PR_ISSUE_TEMPLATE

### ISSUE THREAD

**Issue by y-martinez** [meedan/check#36]
**Tell us about your request**
When open-source projects grow and begin to receive many PR, a template should be followed to make the PR, this way the order is maintained in the project, as well as PR spam, can be avoided.

**Which service(s) is this request for?**
Let us know which services(s) you want this for?
- Check Doc Project

**Are you currently working around the issue?**
I would like to work on this issue, but tell me if this feature interests you.

**Additional context**
As Check has different components, the template would be helpful to link it correctly with the corresponding issue (if it exists).

**Comment by sanket-bhatt** [comment]
Hi! I could try and help out with this if you would like!

**Comment by akshitadixit** [comment]
Hey @y-martinez please assign this to me, you can have a look at my project's multiple [PR templates](https://github.com/DSC-IIIT-Kalyani/ENCODN/issues/new/choose) to know that I'll do this task efficiently

**Comment by danielafeitosa** [comment]
Hi! Thank you all for your interest!
@y-martinez, this feature is not something we are interested for now (during Hacktoberfest). We hope you can work on another issue :slightly_smiling_face:
