### ISSUE TITLE
OCR for images

### ISSUE THREAD

**Issue by computermacgyver** [meedan/check#47]
Per the conversation with @josselineperdomo on #11 I'm creating a new issue here for extracting text from images. 

This will be a new endpoint in [Alegre](https://github.com/meedan/alegre), the media analysis service that runs with Check.

**Tell us about your request**
Add the ability to extract text from images to Alegre

**Which service(s) is this request for?**
- Alegre

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
When an image is added to Check, we currently only perform image hashing and check for similar images. It would be very useful to fact-checkers to be able to search for text within images and/or to use this text as part of identifying similar images.

This feature request is for the first step: identifying and extracting text from images.

**Additional context**
- In Alegre, add an endpoint `image/ocr` in a new controller `image_ocr_controller`.  [image_similarity_controller](https://github.com/meedan/alegre/blob/ed10801ca826613caca168e101e452274c5d82e1/app/main/controller/image_similarity_controller.py#L22) may be a useful guide.
- This new controller needs only do one thing: accept a url to an image and return a JSON payload with any text detected within the image
- If possible, please add a unit test
- English is a useful place to start, but ideally we would be able to identify text in a wide range of languages (Hindi, Bengali, Portuguese, and Filipino are important languages for partners using Check currently).
- This tutorial may be a useful starting point: [A comprehensive guide to OCR with Tesseract, OpenCV and Python](https://nanonets.com/blog/ocr-with-tesseract/)

A PR should be submitted against the Alegre repository.

**Comment by caiosba** [comment]
We have this feature now.
