### ISSUE TITLE
Upgrade Check service to provide a UI to its API via OpenAPI

### ISSUE THREAD

**Issue by infojunkie** [meedan/check#7]
**Tell us about your request**
Check currently uses Swagger 0.x to expose its API on a web page. Upgrade Swagger to use the latest version of OpenAPI (3.x). Evaluate [OpenAPI Generator](https://openapi-generator.tech/) as possible technology.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Testing and debugging an API during development is much easier when a UI exists to make API calls.

**Comment by sneha-mehta** [comment]
Can I work on this??

**Comment by danielafeitosa** [comment]
@BhuwanChandra and @sneha-mehta are you still interested in working in this issue?
If you are interested, you can check this good example of what is needed here: https://github.com/meedan/pender/pull/233
