### ISSUE TITLE
Upgrade Alegre service to provide a UI to its API via OpenAPI

### ISSUE THREAD

**Issue by infojunkie** [meedan/check#9]
**Tell us about your request**
[Alegre](https://github.com/meedan/alegre)  currently uses Swagger 0.x to expose its API on a web page. Upgrade Swagger to use the latest version of OpenAPI (3.x). Evaluate [OpenAPI Generator](https://openapi-generator.tech/) as possible technology.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Testing and debugging an API during development is much easier when a UI exists to make API calls.

**Comment by karlmarx** [comment]
I would like to be assigned this issue please.

**Comment by infojunkie** [comment]
Thanks @karlmarx for your interest! Feel free to submit a PR for Alegre.

**Comment by king-11** [comment]
@karlmarx are you still working on it?

**Comment by karlmarx** [comment]
> @karlmarx are you still working on it?

I haven't had time lately because of work, so feel free.

**Comment by king-11** [comment]
ok thanks @infojunkie i will start working on this hopefully will send a pr soon

**Comment by danielafeitosa** [comment]
@king-11, if you are still interested, you can check this good example of what is needed here: meedan/pender#233

**Comment by king-11** [comment]
@danielafeitosa am really sorry completely forgot about it due to some issues I will start working on it.

**Comment by danielafeitosa** [comment]
This is great, @king-11! Let us know if you need help

**Comment by king-11** [comment]
@danielafeitosa need a bit on help in setting up server after running the script when i open localhost:3333 it isn't showing anything
